### ISSUE TITLE
Add stage for pathway name conventions

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/academy#17]
See also edits made by Eric Weitz; perhaps combine with adding PW ontology?

**Comment by khanspers** [comment]
@DeniseSl22 : What about if we add a step to the last two steps in pathway curation tracks (purple and orange) to specify a name that follows the convention before upload? Seems more consistent than to have them upload something with an incorrect title just to change it later.

For example:

1. Add a step for changing the pathway name in PathVisio here: https://new.wikipathways.org/academy/stages/met-1-last/index.html (before the "save local file" step)
2. Add a similar step here: https://new.wikipathways.org/academy/stages/fig-met-1-last/index.html

**Comment by DeniseSl22** [comment]
Yes, great idea! I do think the https://new.wikipathways.org/academy/stages/met-1-last/index.html step would fit best, although it already has a lot of info people need to follow... And, we also don't have guidelines on what we want for the names of PWs, right? I could have a talk with @eweitz about this.

**Comment by eweitz** [comment]
Hi!  I typically refine titles using existing [pathway name guidelines](https://www.wikipathways.org/index.php/Help:Guidelines#Pathway_naming) and a few additional elements of style:

* **Use sentence case**.  Write words as they appear in a sentence, e.g. have titles likes "Activation of NLRP3 inflammasome by SARS-CoV-2" instead of "Activation of NLRP3 Inflammasome by SARS-CoV-2".  Note the lowercase "i" in "inflammasome".  This style is used in _Nature_, _Science_, and Wikipedia, among many other publications.  An email thread among core editors agreed this made sense.

* **Use "signaling" instead of "signalling"**.  The former was more prevalent before; my edits made it universal.  This orthographic difference pops up rather frequently.

There are finer points, but the existing guidelines plus those two points likely cover ~95% of cases.  Consistent titles help readability in downstream applications, like [related genes ideogram](https://eweitz.github.io/ideogram/related-genes?org=homo-sapiens&q=NF2), that build on WikiPathways.

**Comment by DeniseSl22** [comment]
Hi @eweitz , thanks for contributing here.... If I'm honest, I have never seen this page with "pathway name guidelines" :see_no_evil: ; thank you for pointing it out! And, I believe this page is not completely covered in the Academy, @khanspers . So, we could check which elements would make nice additions.... but, some of these items will change with a new PV release, so we might want to only index which steps are missing, and then add them to the academy only after we know how to model this in PV4.

**Comment by khanspers** [comment]
The guidelines page is not up-to-date, I just updated the pathway name guidelines to what we have agreed on. I don't think we want to necessarily cover all that content in the Academy or elsewhere; it is very old. So, yes, we want to pick only the good parts to incorporate in the Academy or elsewhere.
For now, I can add something about pathway naming to the existing steps in the Academy and we can see what else should be added after PV4.

**Comment by khanspers** [comment]
Added to met-1-last
