### ISSUE TITLE
Step 1 Signalling Protocol

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/academy#47]
[#review](https://github.com/wikipathways/academy/pull/46)
- Check "Pathway attributes interface" --> why is this needed?
- BridgeDb: why is ID mapping for human needed in the first step? Plugin is also not working for PV3.3.0, check for PV3.4.0

**Comment by khanspers** [comment]
The extra instructions regarding the "Pathway Attributes" interface are necessary because there's a [bug](https://github.com/PathVisio/pathvisio/issues/94) where the title cannot be entered unless the interface is closed and reopened. 
There was a typo though, it should have said "Pathway properties" interface, which is what it's actually called. I have updated it.

For BridgeDb, it's not necessary until later steps, so I could move the instructions there if it's confusing. This step was meant as a setup step.
